### PR TITLE
Scala 2.12

### PR DESCRIPTION
**Pull request by jibbers42**
Here is a PR for scala 2.12 support. I don't know anything about travis, but still attempted to update the .travis.yml file after a quick look at the docs - hope it's right.

The libs for macros and scalatest needed to be updated for 2.12 support and I went ahead and bumped typesafe config too.

### CODE REVIEW

**Comment by mrvisser** [comment]
Thanks @jibbers42 ! I'll work on getting this published, but me publishing to sonatype is so rare that I might have to work out some kinks.

> I went ahead and bumped typesafe config too.

It looks like your intent to upgrade this was rolled back. For posterity, what is the issue here?

**Comment by jibbers42** [comment]
Sorry for the confusion. When updating to 2.12.0, I did at one point intend to update typesafe config to 1.3.1, but since this is a cross build with lower scala versions I decided not to based on info in their readme...
https://github.com/typesafehub/config#binary-releases

> Version 1.2.1 and earlier were built for Java 6, while newer versions (1.3.0 and above) will be built for Java 8.

Perhaps I accidentally did commit that at one point, not sure. @Philippus upgraded the branch to 2.12.1 and also upgraded typesafe config to 1.3.1. I asked his opinion here https://github.com/jibbers42/sealerate/pull/1#issuecomment-269055358, and he also decided to roll it back.

I'm not sure it even causes an issue currently or if it will in the future, but decided to be safe for now.

**Comment by mrvisser** [comment]
Good find, thanks for that

**Comment by mrvisser** [comment]
@jibbers42 @Philippus This is released in 0.0.5. Thanks for the contribution! What name/company can I add into the contributions listing for 2.12 support?

**Comment by mrvisser** [comment]
FYI could take a bit to sync in the sonatype repos. I'm not seeing it yet.

**Comment by jibbers42** [comment]
You can use jibbers42 for the name, that's fine. Thanks for the release!

**Comment by Philippus** [comment]
You can use 'Philippus Baalman' for me. Thanks for the release as well!

**Pull request merged**
